"""empty message

Revision ID: dbf2878d7e7b
Revises: 5cd93c5f7625
Create Date: 2024-04-27 03:13:55.859931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf2878d7e7b'
down_revision = '5cd93c5f7625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))
        batch_op.drop_constraint('planets_email_key', type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('planets_email_key', ['email'])
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
